similar_skills = {
    "CSS3": ["css", "CSS3", "css3"],
    "HTML5": ["html", "HTML5", "html5"],
    "JavaScript": ["js", "JavaScript", "jscript"],
    "Angular.Js": ["angular", "angular6", "angularjs"],
    "React.JS": ["react", "reactjs", "reactjs2", "reactjs3", "reactjs4"],
    "Node.JS": ["Node", "nodejs"],
    "Vue.JS": ["vue", "vuejs", "vuejs2", "vuejs3", "vuejs4"],
    "Laravel": ["Laravel", "laravelframework", "laravelphp", "laravel5"],
    "Twig": ["twig"],
    "Bootstrap": [
        "bootstrap",
        "bootstrap4",
        "bootstrap3",
        "bootstrap2",
        "bootstrap5",
    ],
    "jQuery": ["jquery"],
    "PHP": ["php", "phpwebdevelopment"],
    "Python": ["python"],
    "Ruby": ["ruby"],
    "C#": ["csharp"],
    "C++": ["cplusplus"],
    "C": ["c"],
    "Java": ["java"],
    "Clojure": ["clojure"],
    "TypeScrip": ["typescript"],
    " Communication Skills": [
        "communicationskills",
        "communication",
        "communicate",
        "communicationengineering",
    ],
    "Git": ["git"],
    "Responsive": ["responsivedesign"],
    "API": ["api"],
    "AWS": ["aws", "amazonwebservices"],
    "Linux": ["linux", "unix"],
    "MySQL": ["mysql"],
    "PostgreSQL": ["postgresql"],
    "MongoDB": ["mongodb", "Mongodb", "MongoDB"],
    "SQL": ["sql"],
    "NoSQL": ["nosql"],
    "MSSQL": ["mssql", "microsoftsqlserver"],
    "Oracle": ["oracle"],
    "Big Data": ["bigdata"],
    "Visualization": ["datavisualization"],
    "Data Warehousing": ["datawarehousing", "warehouse", "datawarehouse"],
    "Data Integration": ["dataintegration"],
    "Data Cleaning": ["datacleaning"],
    "Data Management": ["datamanagement"],
    "Adobe Photoshop": ["adobephotoshop"],
    "Adobe Illustrator": ["adobeillustrator"],
    "Adobe InDesign": ["adobeindesign"],
    "Adobe XD": ["adobexd"],
    "Adobe After Effects": ["adobeaftereffects"],
    "Adobe Premiere Pro": ["adobepremierepro"],
    "Adobe Lightroom": ["adobelightroom"],
    "Adobe Dreamweaver": ["adobedreamweaver"],
    "Adobe Flash": ["adobeflash"],
    "Adobe Fireworks": ["adobefireworks"],
    "Adobe Flash Builder": ["adobeflashbuilder"],
    "Adobe Flash Catalyst": ["adobeflashcatalyst"],
    "Ionic Framework": ["ionicframework", "ionic"],
    "Agile": [
        "agile",
        "agilemethodologies",
        "agilemethodology",
        "agilemethodology",
    ],
    "Django": ["django"],
    "Ajax": ["ajax"],
    "RESTful": ["restful", "restfulapis", "restapis"],
    "Nuxt": ["nuxt", "nuxt3", "nuxt2"],
    "Next.js": ["nextjs", "next"],
    "React Native": ["reactnative"],
    "Tailwind CSS": "tailwindcss",
    "Express": ["express"],
    "Spring Boot": ["springboot"],
    "Figma": ["figma"],
    "ASP.NET": [
        "aspnet",
        "asp",
        "net",
        "netcore",
        "asp.net",
        "netwebforms",
        "netframework",
        "netwebapi",
        "netmvc",
    ],
    "Go": ["go", "golang"],
    "Docker": ["docker"],
    "MVC Architecture": ["mvc", "modelviewcontroller", "mvcarchitecture"],
    "JSON": ["json", "jsonapis", "jsonapi"],
    "YAML": ["yaml", "yml", "ymlfile"],
    "XML": ["xml"],
    "OOP": ["oop", "objectorientedprogramming"],
    "Oracle": ["oracle", "oracle11g", "oracle10g"],
    "CI/CD": [
        "ci/cd",
        "continuousintegration/continuousdelivery",
        "ci",
        "cd",
        "cicd",
    ],
    "Cloud": ["cloud", "cloudcomputing", "cloudservices"],
    "Pipeline Management": ["pipelinemanagement", "pipeline"],
    "Bash Scripting": ["bash", "bashscripting"],
    "Azure": ["azure", "azurefunctions", "azurepipelines", "azuredevopsserver"],
    "Networking": ["networking", "network"],
    "Kubernetes": ["kubernetes", "k8s"],
    "GitHub": ["github", "gitlab"],
    "Jenkins": ["jenkins", "jenkinsci", "jenkinsci.org"],
    "Mongodb": [
        "mongodb",
        "mongodb3",
        "mongodb2",
        "mongodb1",
        "mongodb4",
        "mongodb5",
        "mongodb6",
    ],
    "Hadoop": ["hadoop", "hadoop2", "hadoop1", "hadoop3", "hadoop4", "hadoop5"],
    "Statistics": ["statistics", "statisticalanalysis", "Analysis", "analysis"],
    "NLP": ["nlp", "naturallanguageprocessing"],
    "Data Base": ["database", "databases", "db", "dbs"],
    "Git Flow": ["gitflow", "gitflowworkflow"],
    "AutoCAD": ["autocad"],
    "Redux": ["redux"],
    "GraphQL": ["graphql", "GraphQL"],
    "Elasticsearch": ["elasticsearch", "elastic"],
    "Research": [
        "research",
        "researcher",
        "researchers",
        "researching",
        "researches",
    ],
    "Travis-CI": ["travisci", "travis-ci", "travis", "travisci.org"],
    "MEAN stack": [
        "meanstack",
        "meanstackframework",
        "meanstackjs",
        "meanstackphp",
    ],
    "MERN stack": ["mernstack", "mernstackframework", "mernstackjs"],
    "Naive Bayes": ["naivebayes", "naive bayes", "naive bayes classifier"],
    "K-Nearest Neighbors": [
        "knn",
        "k-nearest neighbors",
        "k nearest neighbors",
    ],
    "Decision Tree": [
        "decisiontree",
        "decision tree",
        "decision tree classifier",
    ],
    "Random Forest": [
        "randomforest",
        "random forest",
        "random forest classifier",
    ],
    "Logistic Regression": ["logisticregression", "logistic regression"],
    "Linear Regression": ["linearregression", "linear regression"],
    "SVM": ["svm", "svmclassifier", "svmclassifiers", "svmclassification"],
    "K-Means": ["kmeans", "k-means", "k means"],
    "Clustering": ["clustering", "clusteringalgorithms", "clusteringalgorithm"],
    "Pandas": ["pandas", "pandasdataframe", "pandasdataframes", "pandasdata"],
    "NumPy": ["numpy", "numpyarray", "numpyarrays", "numpyarrays"],
    "SciPy": ["scipy", "scipyarray", "scipyarrays", "scipyarrays"],
    "Scikit-Learn": ["scikit-learn", "scikit-learn", "scikit-learn", "scikit"],
    "Matplotlib": ["matplotlib", "matplotlibplot", "matplotlibplots"],
    "Seaborn": ["seaborn", "seabornplot", "seabornplots"],
    "TensorFlow": ["tensorflow", "tensorflow2", "tensorflow1"],
    "PyTorch": ["pytorch", "pytorch2", "pytorch1"],
    "Scikit-Image": ["scikit-image"],
    "Scikit-Learn": ["scikit-learn"],
    "Scikit-Optimize": ["scikit-optimize"],
    "Scikit-Garden": ["scikit-garden"],
    "Image recognition": ["imagerecognition"],
    "Google Cloud": [
        "gcp",
        "google cloud platform",
        "google cloud",
        "google cloud services",
    ],
    "VSTS": [
        "vsts",
        "visualstudio",
        "visualstudio.com",
        "visualstudioonline",
        "visualstudioonline.com",
        "Microsoft Visual Studio Team Services",
    ],
    "Kotlin": ["kotlin"],
    "Swift": ["swift"],
    "Rust": ["rust"],
    "Scala": ["scala"],
    "Haskell": ["haskell"],
    "Unity": ["unity", "unity3d"],
    "Unreal Engine": ["unrealengine", "unreal"],
    "Blender": ["blender"],
    "OpenGL": ["opengl"],
    "Vulkan": ["vulkan"],
    "DirectX": ["directx"],
    "Firebase": ["firebase"],
    "Flask": ["flask"],
    "PyQt": ["pyqt"],
    "Tkinter": ["tkinter"],
    "Electron": ["electron"],
    "Jupyter": ["jupyter", "jupyterlab"],
    "Puppeteer": ["puppeteer"],
    "Selenium": ["selenium"],
    "Beautiful Soup": ["beautifulsoup", "bs4"],
    "Flask-RESTful": ["flask-restful"],
    "Django REST framework": ["djangorestframework"],
    "FastAPI": ["fastapi"],
    "Swagger": ["swagger"],
    "GraphQL": ["graphql"],
    "RxJava": ["rxjava"],
    "RxJS": ["rxjs"],
    "Retrofit": ["retrofit"],
    "OkHttp": ["okhttp"],
    "Spring": ["spring"],
    "Spring Security": ["springsecurity"],
    "Hibernate": ["hibernate"],
    "MyBatis": ["mybatis"],
    "JUnit": ["junit"],
    "Mockito": ["mockito"],
    "PowerMock": ["powermock"],
    "TestNG": ["testng"],
    "Robot Framework": ["robotframework"],
    "Jest": ["jest"],
    "Mocha": ["mocha"],
    "Chai": ["chai"],
    "Enzyme": ["enzyme"],
    "Cypress": ["cypress"],
    "SpecFlow": ["specflow"],
    "NUnit": ["nunit"],
    "PHPUnit": ["phpunit"],
    "RSpec": ["rspec"],
    "Cucumber": ["cucumber"],
    "SoapUI": ["soapui"],
    "Postman": ["postman"],
    "Apigee": ["apigee"],
    "Kong": ["kong"],
    "NGINX": ["nginx"],
    "Apache": ["apache"],
    "IIS": ["iis"],
    "Django Channels": ["django-channels"],
    "WebSockets": ["websocket"],
    "GraphQL Yoga": ["graphql-yoga"],
    "Apollo Client": ["apollo-client"],
    "Apollo Server": ["apollo-server"],
    "Redux Saga": ["redux-saga"],
    "MobX": ["mobx"],
    "Vuex": ["vuex"],
    "Redux Thunk": ["redux-thunk"],
    "NGRX": ["ngrx"],
    "Flux": ["flux"],
    "Webpack": ["webpack"],
    "Rollup": ["rollup"],
    "Parcel": ["parcel"],
    "Gulp": ["gulp"],
    "Grunt": ["grunt"],
    "Babel": ["babel"],
    "ESLint": ["eslint"],
    "Prettier": ["prettier"],
    "TSLint": ["tslint"],
    "Husky": ["husky"],
    "Jasmine": ["jasmine"],
    "Karma": ["karma"],
    "Nightwatch": ["nightwatch"],
    "Appium": ["appium"],
    "Detox": ["detox"],
    "Playwright": ["playwright"],
    "Firebase Test Lab": ["firebase-test-lab"],
    "XCTest": ["xctest"],
    "Newman": ["newman"],
    "Karate": ["karate"],
    "Artillery": ["artillery"],
    "K6": ["k6"],
    "Locust": ["locust"],
    "JMeter": ["jmeter"],
    "Gatling": ["gatling"],
    "BlazeMeter": ["blazemeter"],
    "Apache Bench": ["apachebench", "ab"],
    "Loader.io": ["loaderio"],
    "WebPagetest": ["webpagetest"],
    "Selenium Grid": ["selenium-grid"],
    "Docker Compose": ["docker-compose"],
    "Kubernetes": ["kubernetes", "k8s"],
    "Nomad": ["nomad"],
    "Helm": ["helm"],
    "Terraform": ["terraform"],
    "AWS CloudFormation": ["aws-cloudformation"],
    "Azure Resource Manager": ["azurerm"],
    "Google Cloud Deployment Manager": ["gcp-deployment-manager"],
    "Vagrant": ["vagrant"],
    "Ansible": ["ansible"],
    "Puppet": ["puppet"],
    "Chef": ["chef"],
    "SaltStack": ["saltstack"],
    "Capistrano": ["capistrano"],
    "Fabric": ["fabric"],
    "Maven": ["maven"],
    "Gradle": ["gradle"],
    "Apache Ant": ["apache-ant"],
    "SBT": ["sbt"],
    "Yarn": ["yarn"],
    "npm": ["npm"],
    "pip": ["pip"],
    "NuGet": ["nuget"],
    "Chocolatey": ["chocolatey"],
    "Composer": ["composer"],
    "Dart": ["dart"],
    "Flutter": ["flutter"],
    "Deno": ["deno"],
    "RabbitMQ": ["rabbitmq"],
    "Kafka": ["kafka"],
    "ActiveMQ": ["activemq"],
    "ZeroMQ": ["zeromq"],
    "Redis": ["redis"],
    "Memcached": ["memcached"],
    "MongoDB": ["mongodb"],
    "Cassandra": ["cassandra"],
    "Couchbase": ["couchbase"],
    "CouchDB": ["couchdb"],
    "Elasticsearch": ["elasticsearch"],
    "Solr": ["solr"],
    "Neo4j": ["neo4j"],
    "ArangoDB": ["arangodb"],
    "InfluxDB": ["influxdb"],
    "Prometheus": ["prometheus"],
    "Grafana": ["grafana"],
    "Kibana": ["kibana"],
    "Logstash": ["logstash"],
    "Beats": ["beats"],
    "OpenTelemetry": ["opentelemetry"],
    "Zipkin": ["zipkin"],
    "Jaeger": ["jaeger"],
    "AppDynamics": ["appdynamics"],
    "New Relic": ["newrelic"],
    "Dynatrace": ["dynatrace"],
    "DataDog": ["datadog"],
    "Splunk": ["splunk"],
    "Sumo Logic": ["sumologic"],
    "Loggly": ["loggly"],
    "Logentries": ["logentries"],
    "Papertrail": ["papertrail"],
    "Graylog": ["graylog"],
    "Seq": ["seq"],
    "WordPress": ["wordpress", "wordpresscom", "wp"],
    "microservices": [
        "microservices",
        "micro service",
        "micro-services",
        "micro-service",
    ],
}


def clean_skills(skills, similar_skills):
    found = False
    cleaned_skills = set()
    for skill in skills:
        for key, value in similar_skills.items():
            for val in value:
                if skill.lower() == val.lower() or skill.lower() == key.lower():
                    cleaned_skills.add(key)
                    found = True
                    break
        if not found:
            cleaned_skills.add(skill)

    return cleaned_skills
